[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "RoBiTE"
version = "0.0.2-alpha"
description = "Rotary Bidirectional Transformer Encoder. For use with multi-dimensional sparse data."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Uros Zivanovic", email = "uros.zivanovic@studenti.units.it"}
]
dependencies = [
    "torch",
    "numpy",
    "wandb",
    "pydantic-settings",
    "accelerate",
    "safetensors"
]

[project.urls]
Repository = "https://github.com/Chromeilion/SEFT"

[tool.setuptools.packages.find]
include = ["robite"]